source 'https://rubygems.org'
ruby '2.7.1'

gem 'dotenv'
gem 'forecast_io'
gem 'httparty'
gem 'i18n'
gem 'net-http-persistent'
gem 'nokogiri'
gem 'openssl'
gem 'pry'
gem 'telegram-bot-ruby'
gem 'tzinfo'
