source 'https://rubygems.org'
ruby '3.2.2'

gem 'dotenv'
gem 'httparty'
gem 'i18n'
gem 'net-http-persistent'
gem 'nokogiri'
gem 'openssl', '3.1.0'
gem 'pry'
gem 'rss'
gem 'telegram-bot-ruby'
gem 'tzinfo'
